import type { Metadata } from "next";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
      <head>
	  	<meta name="google-signin-client_id" content="168035031127-ds3li8n2opm57a57bqd3h9a9lsrecuma.apps.googleusercontent.com"></meta>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="beforeInteractive"
        />
		<Script src="https://apis.google.com/js/api:client.js" />
      </head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<GoogleOAuthProvider
					clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
				>
					{children}
				</GoogleOAuthProvider>
			</body>
		</html>
	);
}
